fix: implicit QString conversion error
linuxdeepin/deepin-terminal pull request #103
Opened 2021-10-17 07:09 UTC by huangz986

"const char*" to "QString" conversion is private in newer Qt versions by default, "char" to "QChar" likewise.
Either simply disable macros QT_NO_CAST_FROM_ASCII and QT_NO_CAST_TO_ASCII, or wrap those string literals with functions like QString:fromUtf8(). This commit chooses the latter.

Log:  fix implicit QString conversion error

#102

2021-11-18 01:27 UTC, ch593030323 commented
Modifying the source code is not a good idea.
U can adjust "deepin-terminal/3rdparty/terminalwidget/CMakeLists.txt" as [https://github.com/linuxdeepin/deepin-terminal/issues/102.](url)
we will close that PR.

2021-11-18 02:30 UTC, zccrs requested changes
There are many of the same problems, please check.

2021-11-18 02:30 UTC, zccrs commented on 3rdparty/terminalwidget/lib/Emulation.cpp
> +    if (QString::fromUtf8(_codec->name()).toUpper().startsWith(QString::fromUtf8("GB")) && !isCommandExec) {
if (_codec->name().startsWith("GB"))

2021-11-18 02:30 UTC, zccrs commented on 3rdparty/terminalwidget/lib/Emulation.cpp
> +    QString utf16Text = QString::fromUtf8("");
No need to assign

2021-11-18 02:30 UTC, zccrs commented on 3rdparty/terminalwidget/lib/Emulation.cpp
> +    if (utf16Text.startsWith(QString::fromUtf8("\u001B]0;")) && utf16Text.endsWith(QString::fromUtf8("\b\b\b\b\b"))) {
startsWith(QLatin1String(...)) endsWith(QLatin1String(...))

2021-11-18 02:30 UTC, zccrs commented on 3rdparty/terminalwidget/lib/Pty.cpp
> +            QString removePattern = QString::fromUtf8("sudo\\s+apt-get\\s+purge\\s+%1").arg(packageName);
QStringLiteral(...).arg();

2021-11-19 08:56 UTC, ch593030323 commented
the many of the same problems is due to the higher Qt Version such as Qt5.15. u can try [https://github.com/linuxdeepin/deepin-terminal/issues/102#issuecomment-957123065](url) that is working in Qt5.15.

2021-11-20 02:58 UTC, huangz986 commented
> Modifying the source code is not a good idea. U can adjust "deepin-terminal/3rdparty/terminalwidget/CMakeLists.txt" like [#102](https://github.com/linuxdeepin/deepin-terminal/issues/102) we will close that PR.

I don't think it's a good idea in the long term, adding MACROs is just a workaround. However, I have no time for further changes any more, so I will close this PR.

2021-11-20 02:59 UTC, closed without merging