chore: use GNUInstallDirs in CmakeLists
linuxdeepin/deepin-terminal pull request #217
Opened 2022-08-17 07:02 UTC by wineee

Log: use GNUInstallDirs in CmakeLists

2023-02-14 08:33 UTC, wineee commented
https://deepin-community.github.io/sig-dde-porting/posts/gnuinstalldirs/

2023-03-06 05:38 UTC, zccrs approved these changes

2023-03-06 05:40 UTC, zccrs requested changes

2023-03-06 05:40 UTC, zccrs commented on 3rdparty/terminalwidget/CMakeLists.txt
> +    set(CMAKE_INSTALL_PREFIX /usr)
是不是可以用 set 的 CACHE 模式代替

2023-03-06 06:16 UTC, wineee commented on 3rdparty/terminalwidget/CMakeLists.txt
> +    set(CMAKE_INSTALL_PREFIX /usr)
CMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT 本身就是用来判断编译者是否有主动赋值的，没有必要加 CACHE

2023-03-06 06:17 UTC, zccrs commented on 3rdparty/terminalwidget/CMakeLists.txt
> +    set(CMAKE_INSTALL_PREFIX /usr)
我的意思是把 set 改成 set CACHE 就不用再判断 CMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT 了

2023-03-06 06:24 UTC, wineee commented on 3rdparty/terminalwidget/CMakeLists.txt
> +    set(CMAKE_INSTALL_PREFIX /usr)
另外这个可以不加， 一般默认 /usr/local， debian/rules 设置 `-DCMAKE_INSTALL_PREFIX=/usr`
按照 fhs 标准，系统管理员直接 `make install` 就是应该安装到 /usr/local, 而系统打包应该是 /usr

2023-03-06 06:33 UTC, wineee commented on 3rdparty/terminalwidget/CMakeLists.txt
> +    set(CMAKE_INSTALL_PREFIX /usr)
> 我的意思是把 set 改成 set CACHE 就不用再判断 CMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT 了

没有必要，CMAKE_INSTALL_PREFIX 已经被定义过了，这样写有点像二次定义
opencv 同时使用了 CMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT 和 CACHE 但是应该没有必要，不清楚这样写的原因
https://github.com/opencv/opencv/blob/0052d46b8e33c7bfe0e1450e4bff28b88f455570/CMakeLists.txt#L127-L138

2023-03-06 06:55 UTC, zccrs commented on 3rdparty/terminalwidget/CMakeLists.txt
> +    set(CMAKE_INSTALL_PREFIX /usr)
> 

既然这样建议去掉，不要设置

2023-03-06 07:27 UTC, wineee commented on 3rdparty/terminalwidget/CMakeLists.txt
> +    set(CMAKE_INSTALL_PREFIX /usr)
看了下代码，尽管没有冲突， v23 还是有变化的需要重新提个

2023-03-06 07:27 UTC, closed without merging