feat: Add option to control the length of Quake window animation
linuxdeepin/deepin-terminal pull request #252
Opened 2023-02-17 01:23 UTC by ArchieMeng

Add a slider in advanced settings to control the duration of Quake window animation

2023-02-17 02:54 UTC, ArchieMeng commented
/recheck

2023-02-17 02:56 UTC, ArchieMeng commented
/check build

2023-02-17 03:01 UTC, zccrs requested changes
只需要修改 deepin-terminal.ts 和  deepin-terminal_zh_CN.ts，其他语言不要在这里改动。

2023-02-17 03:01 UTC, zccrs commented on src/assets/other/default-config.json
> +                            "name": "Quake window duration",
这里是说窗口出来或隐藏时的动画时长吗？建议加上 Animation：`Quake window Animation duration`

2023-02-17 03:01 UTC, zccrs commented on src/main/mainwindow.cpp
> +    int quakeAnimationHighDistributionTotalTime = Settings::instance()->QuakeDuration() / 3;
这里为什么要除以3呢

2023-02-17 03:01 UTC, zccrs commented on src/main/mainwindow.cpp
> +    int quakeAnimationBaseTime = Settings::instance()->QuakeDuration() * 2 / 3;
这个值有什么用途？

2023-02-17 03:01 UTC, zccrs commented on src/main/service.cpp
> +    m_settingDialog->widgetFactory()->registerWidget("valslider", Settings::createValSliderHandle);
动画时间用slider不方便控制具体的值呀。是不是用 spinbox 会更适合些

2023-02-17 03:01 UTC, zccrs commented
上个效果图看一下

2023-02-17 03:27 UTC, ArchieMeng commented on src/assets/other/default-config.json
> +                            "name": "Quake window duration",
是的，指的是动画．

2023-02-17 03:28 UTC, ArchieMeng commented on src/main/mainwindow.cpp
> +    int quakeAnimationHighDistributionTotalTime = Settings::instance()->QuakeDuration() / 3;
保持原来的quakeAnimationBaseTime和quakeAnimationHighDistributionTotalTime的时间比例．

2023-02-17 03:29 UTC, ArchieMeng commented on src/main/mainwindow.cpp
> +    int quakeAnimationBaseTime = Settings::instance()->QuakeDuration() * 2 / 3;
这个是不随雷神窗口高度变动的动画时长．

2023-02-17 03:32 UTC, ArchieMeng commented on src/main/service.cpp
> +    m_settingDialog->widgetFactory()->registerWidget("valslider", Settings::createValSliderHandle);
我的理解是动画时长是很感官上的，不需要精准控制具体的值，能方便地拉到合适的时长就够了．spinbox没法做到这样．

2023-02-17 03:36 UTC, ArchieMeng commented
效果如视频所示：

https://user-images.githubusercontent.com/12139431/219543133-57dc487d-c608-4061-9177-61f3088f1845.mp4

2023-02-20 01:30 UTC, ArchieMeng commented
https://user-images.githubusercontent.com/12139431/219989388-33306016-01d8-4ac1-8bb3-8beebb2e67d5.mp4

当前效果．

2023-02-20 01:34 UTC, zccrs approved these changes

2023-02-20 01:35 UTC, zccrs requested changes

2023-02-20 01:35 UTC, zccrs commented on src/settings/settings.cpp
> +    valTicksList << tr("Long");
建议用“快”和“慢”来表示

2023-02-20 03:23 UTC, ArchieMeng commented on src/settings/settings.cpp
> +    valTicksList << tr("Long");
修改好了．

2023-02-20 03:25 UTC, zccrs approved these changes

2023-02-20 03:28 UTC, merged