feat: 废弃DDE-Daemon字体接口，改用fontconfig
linuxdeepin/deepin-terminal pull request #257
Opened 2023-03-03 10:08 UTC by ArchieMeng

字体功能将不再依赖DDE-Daemon提供的接口，改为使用fontconfig来获取．
基本保持和DDE-Daemon对应接口的实现一致．
fix https://github.com/linuxdeepin/developer-center/issues/3392

Log: 废弃DDE-Daemon字体接口，改用fontconfig

2023-03-06 01:40 UTC, xzl01 commented
代码改动 对应的SPDX头也需要改动

2023-03-06 02:04 UTC, zsien commented
getFonts 可以直接用 QFontDatabase 吧

2023-03-06 02:30 UTC, ArchieMeng commented
> getFonts 可以直接用 QFontDatabase 吧

试过了，但不太行．因为会少字体，比如文泉驿．

2023-03-06 02:35 UTC, zccrs requested changes

2023-03-06 02:35 UTC, zccrs commented on src/common/utils.cpp
> +         if (!FONT_BLACKLIST.contains(family) && (spacing == "100" || family.toLower().contains("mono"))) {
"100" 可以改用 FC_MONO

2023-03-06 02:35 UTC, zccrs commented on src/common/utils.cpp
> +             qDebug() << families << familyLangs;
日志用 Q_LOGGING_CATEGORY 加 qCDebug 等一系列函数实现，可以参考 dtkcore 等项目。
另外，日志输出的内容不能这么随意，这样的内容应该只是在本地debug时需要看，在正式代码中没有意义，对于正式代码的log，必须要能做到脱离代码也能让人理解这条log的意思。

2023-03-06 02:35 UTC, zccrs commented on CMakeLists.txt
> +include(FindFontconfig)
需要改  debian/control 加依赖吗

2023-03-06 02:35 UTC, zccrs commented on src/common/define.h
> +    "Symbol",
用 QStringLiteral 包裹这些字符串

2023-03-06 02:35 UTC, zccrs commented on src/common/utils.cpp
> +#define max(a,b) ((a) > (b) ? (a) : (b))
这玩意不是有现成的吗，qMax 或 std::max

2023-03-06 02:35 UTC, zccrs commented on src/common/utils.cpp
> +         fprintf(stderr, "Create FcPattern Failed\n");
为什么不用 Qt 的日志输出接口呢

2023-03-06 02:35 UTC, zccrs commented on src/common/utils.cpp
> +    const QString curLang = localeName.startsWith("en") ? "en" : localeName.toLower().replace("_", "-");
为什么en需要特殊处理？

2023-03-06 02:35 UTC, zccrs commented on src/common/utils.cpp
> +         FcPatternDestroy(pat);
容易忘记，建议用 QScopedPointer 这类的智能指针管理它

2023-03-06 02:35 UTC, zccrs commented on src/common/utils.cpp
> +         fprintf(stderr, "Build FcObjectSet Failed\n");
同上，同类不一一指出了。

2023-03-06 02:35 UTC, zccrs commented on src/common/utils.cpp
> +    FcObjectSetDestroy(os);
建议用 QScopedPointer 这类的智能指针管理它

2023-03-06 02:35 UTC, zccrs commented on src/common/utils.cpp
> +    qDebug() << "current lang:" << curLang;
同下文的评论

2023-03-06 02:35 UTC, zccrs commented on src/common/utils.cpp
> +         const QString rawFamily((char*)FcPatternFormat(fc, (FcChar8*)"%{family}"));
这些获取到的char*内容都不需要销毁吗？
另外不要用QString，这里用 QByteArray更合适

2023-03-06 02:35 UTC, zccrs commented on src/common/utils.cpp
> +    for (auto font = fontMap.begin(); font != fontMap.end(); font++) {
用QMap仅仅是为了去重？

2023-03-06 02:39 UTC, zccrs requested changes

2023-03-06 02:39 UTC, zccrs commented on src/common/utils.cpp
> +         char *charset = (char*)FcPatternFormat(fcList->fonts[i], (FcChar8*)"%{charset}");
建议用 QByteArray::fromRawData 管理它，QByteArray会帮忙销毁数据。

2023-03-06 03:47 UTC, ArchieMeng commented on CMakeLists.txt
> +include(FindFontconfig)
不需要，QT依赖带了．

> > getFonts 可以直接用 QFontDatabase 吧
> 
> 试过了，但不太行．~因为会少字体，比如文泉驿．~ 使用QFontDatabase筛选等宽字体的时候，会把文泉驿等宽字体筛掉．还得看看为什么会这样．

文泉驿还有一些字体是没有spacing属性的，所以会被筛掉，得用字体名判断是否等宽．

2023-03-06 03:47 UTC, ArchieMeng commented
> > getFonts 可以直接用 QFontDatabase 吧
> 
> 试过了，但不太行．~因为会少字体，比如文泉驿．~ 使用QFontDatabase筛选等宽字体的时候，会把文泉驿等宽字体筛掉．还得看看为什么会这样．

文泉驿还有一些字体是没有spacing属性的，所以会被筛掉，得用字体名判断是否等宽．

2023-03-06 05:39 UTC, ArchieMeng commented on src/common/utils.cpp
> +    const QString curLang = localeName.startsWith("en") ? "en" : localeName.toLower().replace("_", "-");
QLocale中的英语一般是带后缀的，比如"en_US", "en_GB"之类的．而FontConfig中的FamilyLang的英语只有"en"．

2023-03-06 05:49 UTC, ArchieMeng commented on src/common/utils.cpp
> +         FcPatternDestroy(pat);
这里的指针是FontConfig管理的，需要调用Fc开头的方法进行管理．比如FcPatternDestroy．不能改成智能指针．

2023-03-06 06:37 UTC, ArchieMeng commented on src/common/utils.cpp
> +    for (auto font = fontMap.begin(); font != fontMap.end(); font++) {
去重是一部分，更重要的是保存字体键值和字体显示名之间的对应关系．

2023-03-06 07:29 UTC, ArchieMeng commented on src/common/utils.cpp
> +             qDebug() << families << familyLangs;
Category的话，有空再一起重构好了．deepin-terminal的其他地方也没用Category．

2023-03-06 07:33 UTC, zccrs requested changes

2023-03-06 07:33 UTC, zccrs commented on src/common/utils.cpp
> +         FcPatternDestroy(pat);
可以，QScopedPointer支持指定销毁使用的函数

2023-03-06 07:34 UTC, zccrs commented on CMakeLists.txt
> +include(FindFontconfig)
那也应该加，Qt是Qt的，你不能依赖它的debian/control，还是应该自己加一下，不然今后如果Qt不依赖fontconfig了，这个项目就有问题了。

2023-03-06 08:07 UTC, ArchieMeng commented on CMakeLists.txt
> +include(FindFontconfig)
现在加了．

2023-03-09 03:13 UTC, zccrs requested changes

2023-03-09 03:13 UTC, zccrs commented on src/common/utils.cpp
> +         QScopedPointer<const char> charset((char*)FcPatternFormat(fcList->fonts[i], (FcChar8*)"%{charset}"));
加上，QScopedPointerPodDeleter 使用。

2023-03-09 03:13 UTC, zccrs commented on src/common/utils.cpp
> +         const QString familyLang(rawFamilyLangStr.data());
不要用 QString，用QByteArray

2023-03-09 03:14 UTC, zccrs commented on src/common/utils.cpp
> +         const QString familyLang(rawFamilyLangStr.data());
这里的 const char *不需要转换为QString使用，直接用QByteArray更好。

2023-03-09 07:21 UTC, zccrs approved these changes, later dismissed

2023-03-10 02:55 UTC, zccrs approved these changes

2023-03-10 02:56 UTC, merged