feat: Add -C option to enable Compress
linuxdeepin/deepin-terminal pull request #261
Opened 2023-03-11 10:24 UTC by shenmo7192

* feat: enable compress when ssh connect. This is very useful when ssh x forwarding

2023-03-12 13:45 UTC, ArchieMeng commented
Thank you for your contribution. 
However, this change should be reconsidered according to the following information.
```
     -C      Requests compression of all data (including stdin, stdout, stderr, and data for forwarded X11, TCP and UNIX-domain connections).  The compression al‐
             gorithm is the same used by gzip(1).  Compression is desirable on modem lines and other slow connections, but will only slow down things on fast net‐
             works.  The default value can be set on a host-by-host basis in the configuration files; see the Compression option in ssh_config(5).
```
**Compression is desirable on modem lines and other slow connections, but will only slow down things on fast net**

To my understanding, it would be much better if it can be implemented as an optional setting.

2023-03-13 03:25 UTC, shenmo7192 commented
> Thank you for your contribution. However, this change should be reconsidered according to the following information.
> 
> ```
>      -C      Requests compression of all data (including stdin, stdout, stderr, and data for forwarded X11, TCP and UNIX-domain connections).  The compression al‐
>              gorithm is the same used by gzip(1).  Compression is desirable on modem lines and other slow connections, but will only slow down things on fast net‐
>              works.  The default value can be set on a host-by-host basis in the configuration files; see the Compression option in ssh_config(5).
> ```
> 
> **Compression is desirable on modem lines and other slow connections, but will only slow down things on fast net**
> 
> To my understanding, it would be much better if it can be implemented as an optional setting.

I think the compression perform loss is totally acceptable in modern computers, so I think it can be a default.

Also the compression makes it possible to use X11 forwarding on not so good network.

2023-03-13 04:17 UTC, felixonmars commented
-1. It's a burden for lower end boxes, VPS, development boards etc. Hardcoding to force-enable it is not acceptable here.

Please consider utilizing existing ssh_config mechanism, i.e. setting "Compression yes" yourself in either ~/.ssh/config or /etc/ssh/ssh_config either for all hosts, or individually for specific hosts.

2023-03-16 01:19 UTC, ArchieMeng requested changes
Hardcoding is not acceptable here.

2026-03-17 09:03 UTC, closed without merging