feat: 增加终端加粗下划线光标设置选项
linuxdeepin/deepin-terminal pull request #270
Opened 2023-04-10 14:30 UTC by liwl1991

Description: 在终端使用vim编辑文件时,单像素下划线无法快速发现光标位置.使用加粗下划线光标能够快速发现光标位置。特殊情况：当使用vim设置高亮搜索时，因为第三方库的色块宽度问题，会让光标在色块重叠区域呈现为1像素横线。

Log: 增加终端加粗下划线设置选项

2023-04-11 02:55 UTC, ArchieMeng commented
![image](https://user-images.githubusercontent.com/12139431/231043918-bb412343-df5b-4a11-a9a7-dbe6c59e6ab9.png)
粗下标的时候，无法显示光标．

2023-04-11 03:00 UTC, liwl1991 commented
> ![image](https://user-images.githubusercontent.com/12139431/231043918-bb412343-df5b-4a11-a9a7-dbe6c59e6ab9.png) 粗下标的时候，无法显示光标．

因为修改的是第三方库，所以编译之后，需要用编译出来的库，替换掉之前的库就可以了
在build下，查找libterminalwidget5.so.0.14.1
将其复制到：/usr/local/lib/x86_64-linux-gnu/libterminalwidget5.so.0.14.1

2023-04-11 05:45 UTC, ArchieMeng requested changes
稍微改下，问题不大．

2023-04-11 05:47 UTC, ArchieMeng requested changes

2023-04-11 05:47 UTC, ArchieMeng commented on 3rdparty/terminalwidget/lib/TerminalDisplay.cpp
> +        }
建议是像BlockCursor一样，使用fillRect来画；至于要不要像它一样，不被聚焦的情况下用drawRect画框，就先看看效果如何吧．

2023-04-11 05:47 UTC, ArchieMeng commented on 3rdparty/terminalwidget/lib/Emulation.h
> +         */
注释规范为　"A rectangular block which covers the bottom area of the cursor character. Easier to be discovered in vim mode."

2023-04-12 01:26 UTC, liwl1991 commented
> 稍微改下，问题不大．

代码已改，请复审

2023-04-12 01:46 UTC, ArchieMeng approved these changes
LGTM

2023-04-12 01:47 UTC, merged

2023-08-04 05:22 UTC, luodeepin commented
验证通过 
终端 6.0.6

![截图_选择区域_20230804132140](https://github.com/linuxdeepin/deepin-terminal/assets/96416089/6246a0df-9335-437e-beb7-e492b883552f)