feat: 终端设置增加双击选中时设置分隔符号
linuxdeepin/deepin-terminal pull request #273
Opened 2023-04-15 03:20 UTC by liwl1991

Description: 当前终端版本特性仅用部分符号作为长字符串的分隔符号且无法调整，无法应对用户在使用双击复制选中文本时灵活的使用场景。本次提交提供在终端设置选项里面自定义双击选中时分隔符。

Log: 终端设置选项增加双击选中时分隔符号的自定义功能

效果图：
![deepin-terminal](https://user-images.githubusercontent.com/28835628/232180465-493b9dae-0936-4a06-bbf3-22743302410b.png)

2023-04-15 05:23 UTC, liwl1991 commented
代码功能有些问题，正在排查

2023-04-15 05:40 UTC, BLumia commented on 3rdparty/terminalwidget/lib/qtermwidget.cpp
> +void QTermWidget::setTerminalWordCharacters(const QString &wc)
这个变动也强烈建议一并往 qtermwidget 上游提交一份

2023-04-15 06:24 UTC, ArchieMeng requested changes
不错不错，非常实用的功能，而且实现起来需要了解的相关qtermwidget内容也挺多的。（Review了一会，才搞懂怎么实现的，commit的很简洁）
不过有个小Bug: 在我这里，刚启动的时候还是会加载默认的全特殊分隔符规则，需要在termwidget里初始化一下。
另外，我觉得做成选中部分允许包含的特殊符号似乎会更合理一些。有以下好处：
- 符合QTermWidget中的实现逻辑。因为它判定是否应该被选中的时候，会判断_wordCharacters中有没有。所以，实现上直接用自定义的值 setWordCharacters 就实现了，不需要从所有的特殊符号中去除分隔符。
- 当前deepin-terminal默认的选中区域分割符是比较多的。（除 **:@-./_~** 以外的特殊符号都是分割符）所以，一般情况是我选中的内容被无情分割，如果是删除分隔符的花会比较眼花缭乱，但如果是添加选中区域可包含的特殊符号的话，就会相对容易且直观些。

我觉得可以讨论一下这样。Konsole就是这个实现逻辑的，你可以装下体验一下。

2023-04-15 06:24 UTC, ArchieMeng commented on 3rdparty/terminalwidget/lib/TerminalDisplay.cpp
> +,_wordCharacters(QLatin1String("")) //设置为空,使配置文件里的默认字符串在刚启动时生效
这里改变了默认的双击选择区域的规则，应该要和原来保持一致。

2023-04-15 06:24 UTC, ArchieMeng commented on src/assets/other/default-config.json
> +                            "default": "`~!@#$%^&*()-_=+[]\\{}|;:'\",.<>/?"
同TerminalDisplay, 需要和以前的默认规则保持一致。

2023-04-15 06:24 UTC, ArchieMeng commented on translations/deepin-terminal_zh_HK.ts
> +        <source>Double click selection separator</source>
建议添加翻译

2023-04-15 06:24 UTC, ArchieMeng commented on translations/deepin-terminal_zh_TW.ts
> +        <source>Double click selection separator</source>
建议添加翻译。

2023-04-15 06:24 UTC, ArchieMeng commented on src/views/termwidget.cpp
要在termwidget类构建时初始化TerminalDisplay的WordCharacter,否则会加载默认的全分隔符。至少在我这是这样的。

2023-04-15 06:39 UTC, liwl1991 commented on src/views/termwidget.cpp
对，实在void TermWidget::initConnections方法对吧，我还在研究，哈哈

2023-04-15 06:39 UTC, liwl1991 commented on 3rdparty/terminalwidget/lib/TerminalDisplay.cpp
> +,_wordCharacters(QLatin1String("")) //设置为空,使配置文件里的默认字符串在刚启动时生效
对，我也是重新测试发现了你说的bug，赶紧评论说发现了问题，在修，哈哈。
你说的第一点，就是我注释里面的正向选择，就是设置的是什么，双击复制就选择什么。我之所以做成反向选择，主要是想跟xshell保持统一（抄袭），你懂的。既然你觉得正向选择比较好，那我就改下吧，我自己目前用的版本就是正向，哈哈
另外，中文的复制目前是没实现的。也就是当前双击汉字的话，只能选择一个，我改过之后，会复制一句话，直到被截断。
你说的保持一致，我赞同，我也是为了上述原因，才破坏第三方库，我觉得这显然不妥。
那我再改改

2023-04-15 07:34 UTC, ArchieMeng commented on 3rdparty/terminalwidget/lib/TerminalDisplay.cpp
> +,_wordCharacters(QLatin1String("")) //设置为空,使配置文件里的默认字符串在刚启动时生效
~~其实Linux 这边用Konsole 的应该挺多的，抄，啊不，致敬它应该会更合适。~~

2023-04-15 08:42 UTC, liwl1991 commented
已完成，请复审 @ArchieMeng 
后续会将修改提交到上游 @BLumia

2023-04-15 11:39 UTC, liwl1991 commented on 3rdparty/terminalwidget/lib/qtermwidget.cpp
> +void QTermWidget::setTerminalWordCharacters(const QString &wc)
好的，下周我提个pr

2023-04-17 01:54 UTC, ArchieMeng requested changes
再优化下就可以合了．主要还是确定文案，现在实现和最开始不一样了，需要修改．

2023-04-17 01:54 UTC, ArchieMeng commented on src/views/termwidget.cpp
> +void TermWidget::setTermWordCharacters(const QString &wc)
TermWidget可以不需要这个函数，直接使用setTerminalWordCharaters就行了．

2023-04-17 01:54 UTC, ArchieMeng commented on src/views/termwidget.h
> +    void setTermWordCharacters(const QString &wc);
TermWidget可以不需要这个函数，直接使用setTerminalWordCharaters就行了．

2023-04-17 01:54 UTC, ArchieMeng commented on src/assets/other/default-config.json
> +                            "name": "Double click selection separator",
文案应该还需要修改下．用"Include special character(s) in double click selections" / ＂在双击选中区域包含特殊符号＂． @meiyixiang

2023-04-17 01:54 UTC, ArchieMeng commented on src/settings/settings_translation.cpp
> +    auto double_click_selection_separatorText = QObject::tr("Double click selection separator");
同文案修改

2023-04-17 03:21 UTC, liwl1991 commented on src/assets/other/default-config.json
> +                            "name": "Double click selection separator",
是修改name的内容，key的内容需要修改吗？

2023-04-17 03:31 UTC, ArchieMeng commented on src/assets/other/default-config.json
> +                            "name": "Double click selection separator",
也一并修改吧，以后维护的时候对不上应该会很迷惑的．

2023-04-17 05:34 UTC, ArchieMeng commented
不好意思，翻车了，我得看看．

2023-04-17 05:46 UTC, ArchieMeng approved these changes
+1

2023-04-17 05:46 UTC, merged

2023-08-04 05:24 UTC, luodeepin commented
验证通过
终端 6.0.6
![截图_选择区域_20230804132409](https://github.com/linuxdeepin/deepin-terminal/assets/96416089/5200cc84-9c06-455a-81b2-549821c89b5c)