feat: 根据当前标签页更新窗口标题
linuxdeepin/deepin-terminal pull request #285
Opened 2023-07-21 06:14 UTC by ArchieMeng

适配docker无特效模式下对应用窗口的标题显示

Log: 根据当前标签页更新窗口标题

2023-07-25 03:35 UTC, justforlxz commented
应该最终只在 titlechagned 里修改标题栏就好了，不应该做这么多重复的事情。

2023-07-25 05:38 UTC, ArchieMeng commented
> 应该最终只在 titlechagned 里修改标题栏就好了，不应该做这么多重复的事情。

改了。

2023-07-31 07:15 UTC, justforlxz requested changes

2023-07-31 07:15 UTC, justforlxz commented on src/main/mainwindow.cpp
> +    setWindowTitle(QString("%1 - %2").arg(m_tabbar->tabText(m_tabbar->currentIndex())).arg(QObject::tr("Terminal")));
```suggestion
    onTermTitleChanged(m_tabbar->tabText(m_tabbar->currentIndex()));
```

2023-08-01 02:32 UTC, justforlxz approved these changes

2023-08-01 02:32 UTC, merged

2023-08-04 05:20 UTC, luodeepin commented
验证通过
终端 6.0.6

任务栏有部分功能没有实现，当前使用 xprop命令查看字段与标题一致
![截图_选择区域_20230804131842](https://github.com/linuxdeepin/deepin-terminal/assets/96416089/bfdc7db8-ecca-435e-84d3-0bffda20df53)