feat: 优化远程服务器功能的实现
linuxdeepin/deepin-terminal pull request #286
Opened 2023-07-21 07:25 UTC by ArchieMeng

修改了添加分组的操作逻辑
添加了删除服务器的按钮
添加了服务器和分组的分割标签
添加了“添加分组”按钮

Issue: https://github.com/linuxdeepin/developer-center/issues/4602
Log: 优化远程服务器功能的实现

2023-07-25 03:34 UTC, ArchieMeng commented
这个稍等我改一下再Review.

2023-07-27 06:45 UTC, Decodetalkers commented on src/remotemanage/groupconfigoptdlg.cpp
> +      m_headLayout(new QHBoxLayout(this)),
一个widget只能有一个layout吧，head的不需要声明this

2023-07-27 06:57 UTC, ArchieMeng commented on src/remotemanage/groupconfigoptdlg.cpp
> +      m_headLayout(new QHBoxLayout(this)),
可以嵌套的。这里是抄的服务器配置对话框的布局。

2023-07-31 06:01 UTC, Decodetalkers approved these changes

2023-07-31 06:21 UTC, ArchieMeng commented
/check obs

2023-07-31 07:27 UTC, justforlxz requested changes

2023-07-31 07:27 UTC, justforlxz commented on src/remotemanage/groupconfigoptdlg.h
> +    ListView   *m_serverList;
要么只按照一个空格对齐，要么在最右边对齐，最后这两行没有对齐。

2023-07-31 07:27 UTC, justforlxz commented on src/remotemanage/groupconfigoptdlg.h
> +    GroupConfigOptDlg(const QString &groupName = "", QWidget *parent = nullptr);
```suggestion
    GroupConfigOptDlg(const QString &groupName = QString(), QWidget *parent = nullptr);
```

2023-07-31 07:27 UTC, justforlxz commented on src/remotemanage/remotemanagementpanel.cpp
> +    qInfo() << "RemoteManagementPanel show add group config dialog.";
没必要打印吧，有的话可以换成 qCDebug，加当前 class 的一个分类，在这样输出 groupName。

2023-07-31 07:27 UTC, justforlxz commented on src/remotemanage/serverconfigmanager.cpp
> +    qInfo() << "ServerConfigManager fill data to manage panel.";
和上面的打印一样。

2023-07-31 07:27 UTC, justforlxz commented on src/remotemanage/serverconfigmanager.h
> +    ServerConfig& operator=(const ServerConfig &c) {
默认不就是这样吗，还需要手动加吗？

2023-07-31 07:27 UTC, justforlxz commented on src/remotemanage/serverconfigoptdlg.cpp
> +//    setFixedSize(459, 392);
无用的注释

2023-07-31 07:27 UTC, justforlxz commented on src/views/itemwidget.cpp
> +//        m_funcButton->setFocus();
？

2023-07-31 07:27 UTC, justforlxz commented on src/views/listview.cpp
> +    qInfo() << "delete " << key;
打印

2023-08-01 08:33 UTC, justforlxz approved these changes

2023-08-01 08:34 UTC, merged

2023-08-04 03:16 UTC, luodeepin commented
验证通过
deepin-terminal 6.0.6 
![截图_选择区域_20230804111552](https://github.com/linuxdeepin/deepin-terminal/assets/96416089/d6ed6cbb-f744-4b15-8e6d-8b26dbd69821)