feat: 新增Ctrl + 鼠标点击移动光标功能
linuxdeepin/deepin-terminal pull request #341
Opened 2024-03-28 13:30 UTC by DaiZW007

ESC [ pn C        cursor right pn times - stop at far right
ESC [ pn D        cursor left pn times - stop at far left
使用每次移动一格的方式进行光标移动

Log: 新增Ctrl + 鼠标点击移动光标功能

2024-03-29 07:03 UTC, ArchieMeng requested changes
没跑命令的时候工作正常，但如果正在运行命令的话，误操作可能会导致发很多的移位字符，甚至导致终端一直在刷新。比如在htop的时候按ctrl移位。或许在触发移光标的时候判断一下isRunningProcess什么的？大概就是这样一类名字的函数名。

2024-03-29 09:27 UTC, DaiZW007 commented
需要加个翻译，辛苦测试下

2024-04-29 08:18 UTC, ArchieMeng reviewed
补上中文翻译就可以+1了。

2024-05-06 15:31 UTC, ArchieMeng approved these changes
LGTM

2024-05-07 02:08 UTC, ArchieMeng requested changes
不需要手动merge origin/master。这边会直接并入主线的。

2024-05-07 02:18 UTC, ArchieMeng approved these changes

2024-05-07 02:19 UTC, merged