feat: remove the limit of term splitting
linuxdeepin/deepin-terminal pull request #353
Opened 2024-08-22 14:27 UTC by hualet

a feature request from here: https://bbs.deepin.org/post/277237

2024-08-22 14:31 UTC, hualet commented
I have read the CLA Document and I hereby sign the CLA.

2024-08-23 02:04 UTC, rb-union commented
/check clacheck/CLAssistant

2024-08-23 02:11 UTC, rb-union commented
https://github.com/linuxdeepin/deepin-terminal/blob/7a69abbf9cfbaf5be52531aae967d95a72fe3225/src/views/termwidget.cpp#L126
这里有设置最小的宽度限制，小窗口下显示分屏多的话，下面的分屏终端显示会被遮盖。

2024-08-23 02:50 UTC, BLumia commented
recheck

2024-08-23 02:52 UTC, hualet commented
I have read the CLA Document and I hereby sign the CLA.

2024-08-27 02:00 UTC, hualet commented
- [ ] 在中间某个term上分屏，新终端出现的位置不对
- [ ] 拖动分割线以后，终端分屏的尺寸不对
- [ ] 在无法分屏的时候（如何判断？），隐藏或者禁用分屏菜单项

2024-08-30 16:07 UTC, hualet commented
@rb-union  @ArchieMeng  done!

2024-09-01 07:08 UTC, ArchieMeng requested changes
Basically LGTM.
Additionally, a commit message is required by https://github.com/linuxdeepin/deepin-terminal/actions/runs/10635689078/job/29485856049?pr=353

2024-09-01 07:08 UTC, ArchieMeng commented on src/views/termwidget.h
> +    static const int MIN_HEIGHT = 120;
It can be private if CanSplit is a friend function or an object function.

2024-09-01 07:08 UTC, ArchieMeng commented on src/views/termwidget.h
> +static bool CanSplit(TermWidget *term, Qt::Orientation ori) {
It would be better if this is a public member function of TermWidget. Is a static function required here? If so, then why is it required?

2024-09-04 05:24 UTC, ArchieMeng requested changes

2024-09-04 05:24 UTC, ArchieMeng commented on src/main/mainwindow.cpp
> +        if (page && TermWidget::canSplit(page->currentTerminal(), Qt::Vertical)) {
I meant "convert canSplit to object function". So that, the way of calling it becomes
```C++
page->currentTerminal()->canSplit(Qt::Vertical)
```

2024-09-04 05:24 UTC, ArchieMeng commented on src/views/termwidget.cpp
> +bool TermWidget::canSplit(TermWidget *term, Qt::Orientation ori) {
I meant "convert canSplit to object function".

2024-09-08 01:30 UTC, ArchieMeng approved these changes
+1

2024-09-08 01:30 UTC, merged