correct the shift+insert behavior to paste selection
linuxdeepin/deepin-terminal pull request #48
Opened 2020-12-20 10:52 UTC by chenzhiwei

The `shift+insert` behavior in other popular terminals is **paste selection**, so I submit PR to make sure deepin-terminal has same behavior as others.

This will help users easily migrate from another terminal to deepin-terminal.

2020-12-23 07:23 UTC, deepinAdmin reviewed
Patch Set 1:

(3 comments)

代码注释率

2020-12-23 07:23 UTC, deepinAdmin reviewed
Patch Set 1:

commit check success!

2020-12-23 07:23 UTC, deepinAdmin reviewed
Patch Set 1:

cppcheck success!

2020-12-23 17:07 UTC, deepinAdmin requested changes
Patch Set 1: Code-Review-1

2020-12-25 01:36 UTC, juteman commented
HeYa!

Submissions about adding new features that are very difficult to merged. This is because adding new features does not align with the product manager's design.

2020-12-25 01:39 UTC, xmuli commented
And the terminal of Deepin series is always `ctrl + shift + c/v`, which is more in line with the habit; while `shift + insert ` feels more difficult to use (personal opinion)

2020-12-25 03:18 UTC, chenzhiwei commented
`shift + insert` to paste selection is a defacto standard for terminal applications.

With `shift + insert` and `ctrl + shift + v`, users can paste two code snippets at same time(paste selection and paste clipboard).

2020-12-25 03:21 UTC, chenzhiwei commented
@juteman  I think this is fix, not a feature.

I just correct the shortcut to a well-known behavior in other terminal applications.

2020-12-25 06:57 UTC, juteman commented
> @juteman I think this is fix, not a feature.
> 
> I just correct the shortcut to a well-known behavior in other terminal applications.

Well ,I can think this is fix. But product manager does not think so

2021-03-02 08:34 UTC, chenzhiwei commented
@deepinAdmin Are there any new updates on this PR?

2021-04-02 06:41 UTC, chenzhiwei commented
Hello, Deepin 20.2 was released two days ago, and it does not include this enhancement.

Could you tell me the plan on this? If Deepin does not plan to include this enhancement in future, please let me know and I will close this PR.

2021-10-11 09:58 UTC, chenzhiwei commented
@ch593030323 ptal

2021-10-11 11:14 UTC, juteman commented
> Hello, Deepin 20.2 was released two days ago, and it does not include this enhancement.
> 
> Could you tell me the plan on this? If Deepin does not plan to include this enhancement in future, please let me know and I will close this PR.



> Hello, Deepin 20.2 was released two days ago, and it does not include this enhancement.
> 
> Could you tell me the plan on this? If Deepin does not plan to include this enhancement in future, please let me know and I will close this PR.

Sorry, I don't think this pull request will  be taked as I said last year. u can just close it.

2021-10-11 13:39 UTC, chenzhiwei commented
sure

2021-10-11 13:39 UTC, closed without merging